name: Publish Helm Charts

on:
  push:
    branches:
      - main
    paths:
      - 'charts/**'
      - '.github/workflows/release.yml'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.19.0

      - name: Package Helm charts
        run: |
          mkdir -p packaged
          for dir in charts/*/; do
            helm lint "$dir"
            helm package "$dir" -d packaged/
          done

      - name: Rebuild Helm repo index
        run: |
          helm repo index packaged --url https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}
          cp -r packaged/* .

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add *.tgz index.yaml
          git commit -m "Update Helm repo index [skip ci]" || echo "No changes to commit"
          git push origin main
