name: Publish Helm Charts

on:
  push:
    branches:
      - main
    paths:
      - 'charts/**'
      - '.github/workflows/release.yml'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v5

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.19.0

      - name: Package Helm charts
        run: |
          mkdir -p packaged
          for dir in charts/*/; do
            if [ -f "$dir/Chart.yaml" ]; then
              echo "Packaging chart: $dir"
              helm lint "$dir"
              helm package "$dir" -d packaged/
            fi
          done

      - name: Ensure gh-pages branch exists
        run: |
          if ! git ls-remote --exit-code origin gh-pages; then
            echo "gh-pages branch not found. Creating it..."
            git checkout --orphan gh-pages
            git rm -rf .
            echo "Helm repository branch" > README.md
            git add README.md
            git commit -m "Initialize gh-pages branch"
            git push origin gh-pages
            git checkout main
          else
            echo "gh-pages branch already exists."
          fi

      - name: Checkout gh-pages branch
        uses: actions/checkout@v5
        with:
          ref: gh-pages
          path: gh-pages

      - name: Copy packaged charts and rebuild index
        run: |
          mkdir -p gh-pages
          cp -r packaged/* gh-pages/
          cd gh-pages
          helm repo index . --url https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}

      - name: Commit and push to gh-pages
        run: |
          cd gh-pages
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Update Helm repo index [skip ci]" || echo "No changes to commit"
          git push origin gh-pages
